# Generated by Django 6.1 on 2026-08-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='categora',
            field=models.CharField(choices=[('culto', 'Culto'), ('retiro', 'Retiro'), ('reuniao', 'Reunião'), ('outro', 'Outro')], default='outro', max_length=20),
        ),
    ]
