# Generated by Django 6.1 on 2026-08-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_evento_categora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='categora',
            new_name='categoria',
        ),
    ]
